# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml
# This file: cloned from https://github.com/gruntjs/grunt/blob/master/appveyor.yml

# Build version format
version: "{build}"

# Test against this version of Node.js
environment:
  nodejs_version: "6.3.0"

build: off

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  - npm install -g angular-cli
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - node -e 'console.log(process.env);'
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
#   - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
#   - cmd: npm test
  - ng build --prod
cache:
  - node_modules -> package.json                                        # local npm modules